[package]
name = "counter"
version = "0.5.7"
authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]
description = "Simple package to count generic iterables"
repository = "https://github.com/coriolinus/counter-rs"
documentation = "https://docs.rs/counter"
readme = "README.md"
keywords = ["count", "multiset", "bag"]
license = "MIT"
edition = "2018"

[dependencies]
num-traits = "0.2"
fnv = "1.0.7"

[dev-dependencies]
maplit = "1.0"
rand = "0.8.5"
